{"layout":"article.njk","title":"PyPI Subpoenaed by US Department of Justice","date":"2023-05-24T03:00:00.000Z","formattedDate":"2023-5-24","source_link":"https://blog.pypi.org/posts/2023-05-24-pypi-was-subpoenaed/","tags":["python"],"topics":[{"name":"Python","slug":"python"}],"content":"<p>PyPI, the Python Package Index, received three subpoenas for user data from the United States Department of Justice in March and April 2023. The Python Software Foundation (PSF), which manages PyPI, was not provided with context on the legal circumstances surrounding these subpoenas. The PSF determined, with the advice of counsel, that their only course of action was to provide the requested data, which related to five PyPI usernames. </p>\n<p>The PSF is committed to protecting user data from disclosure whenever possible, but in this case, they were legally obligated to comply with the subpoenas. The Director of Infrastructure of the PSF fulfilled the requests in consultation with the PSF&#39;s counsel. </p>\n<p>PyPI and the PSF are committed to the freedom, security, and privacy of their users. This incident has prompted them to revisit their current data and privacy standards to ensure they take into account the varied interests of the Python community. Although PyPI collects very little personal data, the PSF is taking steps to improve their privacy standards to better protect their users&#39; data. </p>\n<p>As developers, it&#39;s important to be aware of incidents like this and to take steps to protect our users&#39; data. We should always be mindful of the data we collect and how we store and handle it. This incident serves as a reminder to review our own data and privacy standards to ensure we are doing everything we can to protect our users.</p>\n"}